/**
 * ==========================================================
 * MeetIQ PDF Service
 * Professional Meeting Report Generator
 * ==========================================================
 */

const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

/* ==========================================================
   Helpers
========================================================== */

function safe(value) {

    if (value === undefined || value === null)
        return "";

    return String(value);

}

function line(doc){

    doc
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke("#dddddd");

    doc.moveDown();

}

function section(doc,title){

    if(doc.y>700){

        doc.addPage();

    }

    doc
        .font("Helvetica-Bold")
        .fontSize(18)
        .fillColor("#4F46E5")
        .text(title);

    line(doc);

}

function bullet(doc,text){

    doc
        .font("Helvetica")
        .fontSize(11)
        .fillColor("#222")
        .text("• "+safe(text),{

            indent:12,

            lineGap:3

        });

}

function subtitle(doc,title){

    doc
        .font("Helvetica-Bold")
        .fontSize(13)
        .fillColor("#111")
        .text(title);

}

function paragraph(doc,text){

    doc
        .font("Helvetica")
        .fontSize(11)
        .fillColor("#333")
        .text(

            safe(text),

            {

                lineGap:4,

                align:"justify"

            }

        );

    doc.moveDown();

}

/* ==========================================================
   Header
========================================================== */

function drawHeader(doc,meeting){

    doc.rect(

        0,

        0,

        doc.page.width,

        100

    )

    .fill("#4F46E5");

    doc
        .fillColor("white")
        .font("Helvetica-Bold")
        .fontSize(26)
        .text(

            "MeetIQ",

            45,

            28

        );

    doc
        .fontSize(11)
        .font("Helvetica")
        .text(

            "AI Meeting Intelligence Report",

            45,

            62

        );

    doc.fillColor("black");

    doc.moveDown(4);

    doc

        .font("Helvetica-Bold")

        .fontSize(22)

        .fillColor("#111")

        .text(

            safe(meeting.title)

        );

    doc.moveDown(.5);

    doc

        .font("Helvetica")

        .fontSize(10)

        .fillColor("#666")

        .text(

            "Meeting Date : " +

            new Date(

                meeting.meetingDate ||

                meeting.createdAt

            ).toLocaleString()

        );

    doc.text(

        "Duration : " +

        Math.round(

            (meeting.duration||0)/60

        )+

        " minutes"

    );

    doc.text(

        "Language : "+

        safe(meeting.language)

    );

    doc.text(

        "AI Model : "+

        safe(meeting.aiModel)

    );

    doc.moveDown();

}

/* ==========================================================
   Footer
========================================================== */

function drawFooter(doc){

    const pages=

        doc.bufferedPageRange();

    for(

        let i=0;

        i<pages.count;

        i++

    ){

        doc.switchToPage(i);

        doc

        .fontSize(8)

        .fillColor("#777")

        .text(

            "Generated by MeetIQ",

            50,

            doc.page.height-40,

            {

                width:

                doc.page.width-100,

                align:"center"

            }

        );

        doc.text(

            `Page ${i+1} of ${pages.count}`,

            50,

            doc.page.height-25,

            {

                width:

                doc.page.width-100,

                align:"center"

            }

        );

    }

}

/* ==========================================================
   PDF Generator
========================================================== */

async function generatePDF(meeting){

    return new Promise((resolve,reject)=>{

        try{

            const folder=

                path.join(

                    __dirname,

                    "..",

                    "uploads",

                    "pdfs"

                );

            if(!fs.existsSync(folder)){

                fs.mkdirSync(

                    folder,

                    {

                        recursive:true

                    }

                );

            }

            const pdfPath=

                path.join(

                    folder,

                    `meeting_${meeting._id}.pdf`

                );

            const doc=

                new PDFDocument({

                    size:"A4",

                    margins:{

                        top:50,

                        left:50,

                        right:50,

                        bottom:50

                    },

                    bufferPages:true

                });

            const stream=

                fs.createWriteStream(

                    pdfPath

                );

            doc.pipe(stream);

            drawHeader(

                doc,

                meeting

            );
                        /* ==========================================================
               Executive Summary
            ========================================================== */

            if(meeting.executiveSummary){

                section(

                    doc,

                    "Executive Summary"

                );

                paragraph(

                    doc,

                    meeting.executiveSummary

                );

            }

            /* ==========================================================
               Meeting Overview
            ========================================================== */

            if(meeting.meetingOverview){

                section(

                    doc,

                    "Meeting Overview"

                );

                paragraph(

                    doc,

                    meeting.meetingOverview

                );

            }

            /* ==========================================================
               Detailed Summary
            ========================================================== */

            if(meeting.detailedSummary){

                section(

                    doc,

                    "Detailed Summary"

                );

                paragraph(

                    doc,

                    meeting.detailedSummary

                );

            }

            /* ==========================================================
               Key Discussion Points
            ========================================================== */

            if(

                meeting.keyDiscussionPoints &&

                meeting.keyDiscussionPoints.length

            ){

                section(

                    doc,

                    "Key Discussion Points"

                );

                meeting.keyDiscussionPoints.forEach(point=>{

                    bullet(

                        doc,

                        point

                    );

                });

                doc.moveDown();

            }

            /* ==========================================================
               Action Items
            ========================================================== */

            if(

                meeting.actionItems &&

                meeting.actionItems.length

            ){

                section(

                    doc,

                    "Action Items"

                );

                meeting.actionItems.forEach((item,index)=>{

                    subtitle(

                        doc,

                        `${index+1}. ${safe(item.text)}`

                    );

                    doc

                    .font("Helvetica")

                    .fontSize(10)

                    .fillColor("#555")

                    .text(

                        "Assignee : "+

                        safe(item.assignee)

                    );

                    doc.text(

                        "Priority : "+

                        safe(item.priority)

                    );

                    if(item.dueDate){

                        doc.text(

                            "Due Date : "+

                            safe(item.dueDate)

                        );

                    }

                    doc.moveDown();

                });

            }

            /* ==========================================================
               Decisions
            ========================================================== */

            if(

                meeting.decisions &&

                meeting.decisions.length

            ){

                section(

                    doc,

                    "Key Decisions"

                );

                meeting.decisions.forEach((decision,index)=>{

                    subtitle(

                        doc,

                        `${index+1}.`

                    );

                    paragraph(

                        doc,

                        decision.text

                    );

                    if(decision.madeBy){

                        doc

                        .font("Helvetica-Oblique")

                        .fontSize(10)

                        .fillColor("#666")

                        .text(

                            "Decision By : "+

                            safe(decision.madeBy)

                        );

                        doc.moveDown();

                    }

                });

            }
                        /* ==========================================================
               Deadlines
            ========================================================== */

            if (

                meeting.deadlines &&

                meeting.deadlines.length

            ) {

                section(

                    doc,

                    "Deadlines"

                );

                meeting.deadlines.forEach((deadline, index) => {

                    subtitle(

                        doc,

                        `${index + 1}. ${safe(deadline.task)}`

                    );

                    doc

                        .font("Helvetica")

                        .fontSize(10)

                        .fillColor("#444")

                        .text(

                            "Deadline : " +

                            safe(deadline.date)

                        );

                    doc.moveDown();

                });

            }

            /* ==========================================================
               Risks
            ========================================================== */

            if (

                meeting.risks &&

                meeting.risks.length

            ) {

                section(

                    doc,

                    "Risks"

                );

                meeting.risks.forEach(risk => {

                    bullet(

                        doc,

                        risk

                    );

                });

                doc.moveDown();

            }

            /* ==========================================================
               Blockers
            ========================================================== */

            if (

                meeting.blockers &&

                meeting.blockers.length

            ) {

                section(

                    doc,

                    "Blockers"

                );

                meeting.blockers.forEach(blocker => {

                    bullet(

                        doc,

                        blocker

                    );

                });

                doc.moveDown();

            }

            /* ==========================================================
               Next Steps
            ========================================================== */

            if (

                meeting.nextSteps &&

                meeting.nextSteps.length

            ) {

                section(

                    doc,

                    "Next Steps"

                );

                meeting.nextSteps.forEach(step => {

                    bullet(

                        doc,

                        step

                    );

                });

                doc.moveDown();

            }

            /* ==========================================================
               Important Quotes
            ========================================================== */

            if (

                meeting.importantQuotes &&

                meeting.importantQuotes.length

            ) {

                section(

                    doc,

                    "Important Quotes"

                );

                meeting.importantQuotes.forEach((quote, index) => {

                    subtitle(

                        doc,

                        `${index + 1}.`

                    );

                    doc

                        .font("Helvetica-Oblique")

                        .fontSize(11)

                        .fillColor("#222")

                        .text(

                            `"${safe(quote.text)}"`

                        );

                    if (quote.speaker) {

                        doc

                            .font("Helvetica")

                            .fontSize(10)

                            .fillColor("#666")

                            .text(

                                "- " +

                                safe(quote.speaker)

                            );

                    }

                    doc.moveDown();

                });

            }

            /* ==========================================================
               Meeting Metrics
            ========================================================== */

            section(

                doc,

                "Meeting Metrics"

            );

            const metrics = meeting.metrics || {};

            doc

                .font("Helvetica")

                .fontSize(11)

                .fillColor("#222");

            doc.text(

                "Total Words : " +

                (metrics.totalWords || 0)

            );

            doc.text(

                "Reading Time : " +

                (meeting.readingMinutes || 1) +

                " minute(s)"

            );

            doc.text(

                "Engagement Score : " +

                (metrics.engagementScore || 0) +

                "%"

            );

            doc.text(

                "Meeting Efficiency : " +

                (metrics.meetingEfficiency || 0) +

                "%"

            );

            doc.text(

                "Processing Time : " +

                (meeting.processingTime || 0) +

                " sec"

            );

            doc.text(

                "AI Model : " +

                safe(meeting.aiModel)

            );

            doc.moveDown(2);
                        /* ==========================================================
               Transcript
            ========================================================== */

            if (

                meeting.fullTranscript &&

                meeting.fullTranscript.trim().length

            ) {

                doc.addPage();

                section(

                    doc,

                    "Meeting Transcript"

                );

                paragraph(

                    doc,

                    meeting.fullTranscript

                );

            }

            /* ==========================================================
               End PDF
            ========================================================== */

            drawFooter(doc);

            doc.end();

            stream.on(

                "finish",

                () => {

                    resolve(pdfPath);

                }

            );

            stream.on(

                "error",

                reject

            );

        }

        catch (error) {

            reject(error);

        }

    });

}

module.exports = {

    generatePDF

};